# Site settings
title: Advanture of BirDOR
email: zbirdor@gmail.com
description: This blog is still on experiment.
baseurl: ""
url: "http://yourdomain.com"
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
permalink: /blog/:year
